# 服务端口号
server:
  port: 8001

# 服务名称
spring:
  application:
    name: cloud-payment-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 520520cw...

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cc.yyf.cloud.pojo
