# 服务端口号
server:
  port: 9997


# 服务名称
spring:
  application:
    name: consul-order
  # consul服务注册中心
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
