# 服务端口号
server:
  port: 8001

# 服务名称
spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud/useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 520520cw...

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cc.yyf.cloud.pojo
